import React, {useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';

const products=[
 {id:'aydin',cat:'grocery',price:550,name:{ar:'أيدين',fr:'Aydin',en:'Aydin'},desc:{ar:'منتج مقترح من الساف',fr:'Suggestion ESSÈF',en:'ESSÈF recommendation'},image:'/assets/products/aydin-grocery.jpg',badge:true},
 {id:'sneakers',cat:'fashion',price:189,name:{ar:'أحذية رياضية',fr:'Baskets',en:'Sneakers'},desc:{ar:'أحذية مريحة وعصرية',fr:'Confortables et modernes',en:'Comfortable and modern'},image:'/assets/products/sneakers.svg'},
 {id:'bag',cat:'fashion',price:129,name:{ar:'حقيبة يومية',fr:'Sac quotidien',en:'Daily bag'},desc:{ar:'عملية وأنيقة',fr:'Pratique et élégante',en:'Practical and elegant'},image:'/assets/products/bag.svg'},
 {id:'headphones',cat:'electronics',price:249,name:{ar:'سماعات لاسلكية',fr:'Écouteurs sans fil',en:'Wireless headphones'},desc:{ar:'صوت واضح',fr:'Son clair',en:'Clear sound'},image:'/assets/products/headphones.svg'},
 {id:'watch',cat:'electronics',price:299,name:{ar:'ساعة ذكية',fr:'Montre connectée',en:'Smart watch'},desc:{ar:'ذكية وعملية',fr:'Intelligente et pratique',en:'Smart and practical'},image:'/assets/products/watch.svg'},
 {id:'coffee',cat:'grocery',price:32,name:{ar:'قهوة',fr:'Café',en:'Coffee'},desc:{ar:'قهوة مختارة',fr:'Café sélectionné',en:'Selected coffee'},image:'/assets/products/coffee.svg'},
 {id:'kitchen',cat:'home',price:79,name:{ar:'مستلزمات المطبخ',fr:'Cuisine',en:'Kitchen essentials'},desc:{ar:'للمنزل',fr:'Pour la maison',en:'For home'},image:'/assets/products/kitchen.svg'},
 {id:'oliveoil',cat:'grocery',price:45,name:{ar:'زيت زيتون',fr:"Huile d'olive",en:'Olive oil'},desc:{ar:'منتج غذائي',fr:'Produit alimentaire',en:'Grocery product'},image:'/assets/products/grocery-oliveoil.svg'},
 {id:'phone',cat:'electronics',price:799,name:{ar:'هاتف ذكي',fr:'Smartphone',en:'Smartphone'},desc:{ar:'تقنية يومية',fr:'Technologie du quotidien',en:'Everyday tech'},image:'/assets/products/phone.svg'}
];
const cats=[['all','الكل','Tout','All'],['fashion','ملابس','Mode','Fashion'],['grocery','بقالة','Épicerie','Groceries'],['electronics','إلكترونيات','Électronique','Electronics'],['home','منزل','Maison','Home']];
const copy={ar:{tag:'كل ما تحتاجه، في مكان واحد',hero:'تسوّق بسهولة. اكتشف أكثر. استمتع.',rec:'اختيار الساف',cats:'التصنيفات',search:'ابحث عن منتج...',shop:'تسوّق الآن',cart:'السلة',account:'حسابي',login:'دخول',register:'إنشاء حساب',logout:'خروج',email:'البريد الإلكتروني',password:'كلمة المرور',name:'الاسم',phone:'الهاتف',welcome:'مرحباً بك في الساف',save:'حفظ',close:'إغلاق',logged:'تم تسجيل الدخول',bad:'بيانات الدخول غير صحيحة',exists:'البريد مستخدم مسبقاً',created:'تم إنشاء الحساب'},fr:{tag:'Tout ce qu’il vous faut, au même endroit',hero:'Achetez facilement. Découvrez plus. Profitez.',rec:'Choix ESSÈF',cats:'Catégories',search:'Rechercher un produit...',shop:'Acheter',cart:'Panier',account:'Mon compte',login:'Connexion',register:'Créer un compte',logout:'Déconnexion',email:'E-mail',password:'Mot de passe',name:'Nom',phone:'Téléphone',welcome:'Bienvenue chez ESSÈF',save:'Enregistrer',close:'Fermer',logged:'Connexion réussie',bad:'Identifiants incorrects',exists:'E-mail déjà utilisé',created:'Compte créé'},en:{tag:'Everything you need, in one place',hero:'Shop easily. Discover more. Enjoy.',rec:'ESSÈF Picks',cats:'Categories',search:'Search products...',shop:'Shop now',cart:'Cart',account:'My account',login:'Login',register:'Create account',logout:'Logout',email:'Email',password:'Password',name:'Name',phone:'Phone',welcome:'Welcome to ESSÈF',save:'Save',close:'Close',logged:'Logged in',bad:'Invalid credentials',exists:'Email already used',created:'Account created'}};

function App(){
 const [lang,setLang]=useState(()=>localStorage.getItem('lang')||'ar'); const [dark,setDark]=useState(()=>localStorage.getItem('theme')!=='light'); const [q,setQ]=useState(''); const [cat,setCat]=useState('all'); const [cart,setCart]=useState(()=>JSON.parse(localStorage.getItem('cart')||'[]')); const [account,setAccount]=useState<any>(null); const [modal,setModal]=useState<'login'|'register'|null>(null); const [toast,setToast]=useState('');
 const t=copy[lang]; const rtl=lang==='ar';
 useEffect(()=>{document.documentElement.lang=lang;document.documentElement.dir=rtl?'rtl':'ltr';localStorage.setItem('lang',lang)},[lang,rtl]); useEffect(()=>{document.documentElement.dataset.theme=dark?'dark':'light';localStorage.setItem('theme',dark?'dark':'light')},[dark]); useEffect(()=>localStorage.setItem('cart',JSON.stringify(cart)),[cart]);
 useEffect(()=>{fetch('/api/me').then(r=>r.ok?r.json():null).then(x=>x&&setAccount(x.user)).catch(()=>{})},[]);
 const shown=useMemo(()=>products.filter(p=>(cat==='all'||p.cat===cat)&&`${p.name[lang]} ${p.desc[lang]}`.toLowerCase().includes(q.toLowerCase())),[cat,q,lang]);
 const add=(p:any)=>{setCart(c=>{const old=c.find(x=>x.id===p.id);return old?c.map(x=>x.id===p.id?{...x,qty:x.qty+1}:x):[...c,{...p,qty:1}]});setToast(`${p.name[lang]} ✓`);setTimeout(()=>setToast(''),1600)};
 const submit=async(e:any,mode:string)=>{e.preventDefault();const fd=new FormData(e.currentTarget);const body=Object.fromEntries(fd);const r=await fetch(`/api/${mode}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(r.ok){setAccount(d.user);setModal(null);setToast(mode==='login'?t.logged:t.created)}else setToast(d.error||t.bad);setTimeout(()=>setToast(''),2500)};
 const logout=async()=>{await fetch('/api/logout',{method:'POST'});setAccount(null)};
 return <div className="app">
  <header><a className="brand" href="#"><img src="/assets/logo.png"/><span>ESSÈF STORE</span></a><nav><a href="#home">{t.shop}</a><a href="#categories">{t.cats}</a><a href="#recommend">{t.rec}</a></nav><div className="actions"><button onClick={()=>setLang(lang==='ar'?'fr':lang==='fr'?'en':'ar')}>AR / FR / EN</button><button onClick={()=>setDark(!dark)}>{dark?'☼':'◐'}</button><button onClick={()=>account?logout():setModal('login')}>👤 {account?account.name:t.account}</button><button>🛒 {t.cart} ({cart.reduce((a,x)=>a+x.qty,0)})</button></div></header>
  <main id="home"><section className="hero"><div><p className="eyebrow">الساف • ESSÈF STORE</p><h1>{t.hero}</h1><p>{t.tag}</p><a className="cta" href="#recommend">{t.shop}</a></div><img src="/assets/hero-banner.png"/></section>
  <section id="categories" className="section"><h2>{t.cats}</h2><div className="chips">{cats.map(c=><button className={cat===c[0]?'active':''} onClick={()=>setCat(c[0])} key={c[0]}>{c[lang==='ar'?1:lang==='fr'?2:3]}</button>)}</div><input className="search" value={q} onChange={e=>setQ(e.target.value)} placeholder={t.search}/></section>
  <section id="recommend" className="section"><div className="section-head"><h2>{t.rec}</h2></div><div className="grid">{shown.map(p=><article className="card" key={p.id}><div className="pic">{p.badge&&<b>ESSÈF</b>}<img src={p.image}/></div><div className="info"><small>{p.cat}</small><h3>{p.name[lang]}</h3><p>{p.desc[lang]}</p><strong>{p.price.toFixed(2)} TND</strong><button className="add" onClick={()=>add(p)}>+ {t.shop}</button></div></article>)}</div></section>
  <section className="lifecycle"><h2>ESSÈF lifecycle</h2><div className="steps"><span>🛒 {lang==='ar'?'اختيار':'Selection'}</span><i>→</i><span>📦 {lang==='ar'?'تجهيز':'Packing'}</span><i>→</i><span>🚚 {lang==='ar'?'توصيل':'Delivery'}</span><i>→</i><span>🏠 {lang==='ar'?'وصول':'Arrival'}</span></div></section></main>
  <footer>© 2026 الساف — ESSÈF STORE · AR · FR · EN</footer>
  {toast&&<div className="toast">{toast}</div>}
  {modal&&<div className="overlay" onClick={()=>setModal(null)}><form className="modal" onSubmit={e=>submit(e,modal)} onClick={e=>e.stopPropagation()}><h2>{modal==='login'?t.login:t.register}</h2>{modal==='register'&&<><input name="name" required placeholder={t.name}/><input name="phone" placeholder={t.phone}/></>}<input name="email" type="email" required placeholder={t.email}/><input name="password" type="password" required minLength={8} placeholder={t.password}/><button className="cta">{modal==='login'?t.login:t.register}</button><button type="button" onClick={()=>setModal(modal==='login'?'register':'login')}>{modal==='login'?t.register:t.login}</button></form></div>}
 </div>
}
createRoot(document.getElementById('root')!).render(<App/>);
